"""
---
title: //mojo:attributes.bzl
description: Attributes used by `mojo_*` rules.
---

Attributes used by `mojo_*` rules.
"""

load("//mojo:providers.bzl", "MojoInfo")

MOJO_COMMON_ATTRS = {
    "compile_flags": attr.string_list(
        doc = """Flags for the compiler.

        Pass a list of strings here. For instance `["-O3", "-std=c++20"]`.

        Split flag pairs `-Xclang -somearg` into separate flags
        `["-Xclang", "-somearg"]`.

        Unavailable to downstream targets.
        """,
    ),
    "compile_string_flags": attr.label_list(
        doc = """Flags for the compiler in the form of `string_flag`s.

        Splits the values of each `string_flag` along colons like so:

        ```python
        load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

        string_flag(
            name = "myflags",
            build_setting_default = "a:b:c",
        )

        mojo_library(
            # ...
            # Equivalent to `compile_flags = ["a", "b", "c"]`
            compile_string_flags = [":myflags"],
        )
        ```

        Useful for externally configurable build attributes, such as generated
        flags from Nix environments.
        """,
    ),
    "defines": attr.string_list(
        doc = """Defines for this target.

        Pass a list of strings here. For instance
        `["MYDEFINE_1", "MYDEFINE_2"]`.

        Unavailable to downstream targets.
        """,
    ),
    "deps": attr.label_list(
        doc = """The dependencies for this target.

        Use `ll_library` targets here. Other targets won't work.
        """,
        providers = [MojoInfo],
    ),
    "includes": attr.string_list(
        doc = """Include paths, relative to the target workspace.

        Uses `-iquote`.

        Useful if you need custom include prefix stripping for dynamic paths,
        for instance the ones generated by `bzlmod`. Instead of
        `compile_flags = ["-iquoteexternal/mydep.someversion/include"]`, use
        `includes = ["include"]` to add the path to the workspace
        automatically.

        Expands paths starting with `$(GENERATED)` to the workspace location in
        the `GENDIR` path.

        Unavailable to downstream targets.
        """,
    ),
    "srcs": attr.label_list(
        doc = """Compilable source files for this target.

        Allowed file extensions: `[".mojo", ".🔥"]`.

        Place headers in the `hdrs` attribute.
        """,
        allow_files = [".mojo", ".🔥"],
    ),
}

MOJO_LIBRARY_ATTRS = MOJO_COMMON_ATTRS

MOJO_BINARY_ATTRS = MOJO_COMMON_ATTRS | {
    "defines": attr.string_list(
        doc = """Defines for this target.

        Pass a list of strings here. For instance
        `["MYDEFINE_1", "MYDEFINE_2"]`.

        Unavailable to downstream targets.
        """,
    ),
    "runtime_data": attr.label_list(
        doc = "Extra files made available during test time.",
        allow_files = True,
    ),
}
